name: fmtya
description: GitHub Action to run yamlfmt

author: norwd
branding:
  icon: edit
  color: blue

runs:
  using: composite
  steps:

    - name: Setup Go
      uses: actions/setup-go@v3

    - name: Install yamlfmt
      shell: bash
      run: |
        go install github.com/google/yamlfmt/cmd/yamlfmt@latest
        ls $GOPATH/bin

    - name: Run yamlfmt
      shell: bash
      run: yamlfmt
