---

name: "Main"
run-name: "Main workflow started by @${{ github.actor }}"
permissions: read-all

on:
  push:

defaults:
  run:
    shell: bash

jobs:

  run-self:
    name: Run fmtya on itself
    runs-on: ubuntu-latest
    steps:
      - uses: norwd/fmtya@v0
