name: "Self Test"
run-name: "Self Test workflow started by @${{ github.actor }}"
on:
  push:
defaults:
  run:
    shell: bash
jobs:
  run-self:
    name: Run fmtya on itself
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run fmtya
        uses: ./
        with:
          token: ${{ secrets.SELF_FMTYA || secrets.GITHUB_TOKEN }}
          yamlfmt-version: v0.6.0
          commit-user-name: norwd
          commit-user-email: 106889957+norwd@users.noreply.github.com
          signing-private-key: ${{ secrets.AUTO_COMMIT_GPG_PRIVATE_KEY_FMTYA }}
          signing-passphrase: ${{ secrets.AUTO_COMMIT_GPG_PASSPHRASE_FMTYA }}
